# Generated by Django 5.0.6 on 2024-07-23 15:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NutritionFacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100, unique=True, verbose_name='Nazwa produktu:')),
                ('energy_value', models.SmallIntegerField(blank=True, verbose_name='Wartość energetyczna:')),
                ('proteins', models.SmallIntegerField(blank=True, verbose_name='Białko:')),
                ('total_fats', models.SmallIntegerField(blank=True, verbose_name='Tłuszcze:')),
                ('saturated_fats', models.SmallIntegerField(blank=True, verbose_name='W tym tłuszcze nasycone:')),
                ('carbohydrates', models.SmallIntegerField(blank=True, verbose_name='Węglowodany:')),
                ('sugars', models.SmallIntegerField(blank=True, verbose_name='W tym cukry:')),
                ('cholesterol', models.SmallIntegerField(blank=True, verbose_name='Cholesterol:')),
                ('fiber', models.SmallIntegerField(blank=True, verbose_name='Błonnik:')),
                ('example', models.BooleanField(default=False, verbose_name='Pozycja dla tabeli wzorcowej')),
            ],
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training_name', models.CharField(blank=True, max_length=100, verbose_name='Nazwa treningu:')),
                ('level_of_experience', models.CharField(max_length=100, verbose_name='Stopień zaawansowania:')),
                ('intensity', models.CharField(max_length=100, verbose_name='Intensywność:')),
                ('kcal_burnt', models.SmallIntegerField(blank=True, verbose_name='Spalone kalorie:')),
                ('trained_part', models.CharField(verbose_name='Trenowana partia mięśni:')),
                ('exercise_1', models.CharField(blank=True, max_length=100, verbose_name='Ćwiczenie 1:')),
                ('exercise_1_sets', models.SmallIntegerField(blank=True, verbose_name='Ilość serii:')),
                ('exercise_1_reps', models.SmallIntegerField(blank=True, verbose_name='Ilość powtórzeń')),
                ('exercise_1_description', models.TextField(blank=True, verbose_name='Opis ćwiczenia 1:')),
                ('exercise_2', models.CharField(blank=True, max_length=100, verbose_name='Ćwiczenie 2:')),
                ('exercise_2_sets', models.SmallIntegerField(blank=True, verbose_name='Ilość serii:')),
                ('exercise_2_reps', models.SmallIntegerField(blank=True, verbose_name='Ilość powtórzeń')),
                ('exercise_2_description', models.TextField(blank=True, verbose_name='Opis ćwiczenia 2:')),
                ('exercise_3', models.CharField(blank=True, max_length=100, verbose_name='Ćwiczenie 3:')),
                ('exercise_3_sets', models.SmallIntegerField(blank=True, verbose_name='Ilość serii:')),
                ('exercise_3_reps', models.SmallIntegerField(blank=True, verbose_name='Ilość powtórzeń')),
                ('exercise_3_description', models.TextField(blank=True, verbose_name='Opis ćwiczenia 3:')),
                ('exercise_4', models.CharField(blank=True, max_length=100, verbose_name='Ćwiczenie 4:')),
                ('exercise_4_sets', models.SmallIntegerField(blank=True, verbose_name='Ilość serii:')),
                ('exercise_4_reps', models.SmallIntegerField(blank=True, verbose_name='Ilość powtórzeń')),
                ('exercise_4_description', models.TextField(blank=True, verbose_name='Opis ćwiczenia 4:')),
                ('exercise_5', models.CharField(blank=True, max_length=100, verbose_name='Ćwiczenie 5:')),
                ('exercise_5_sets', models.SmallIntegerField(blank=True, verbose_name='Ilość serii:')),
                ('exercise_5_reps', models.SmallIntegerField(blank=True, verbose_name='Ilość powtórzeń')),
                ('exercise_5_description', models.TextField(blank=True, verbose_name='Opis ćwiczenia 5:')),
            ],
        ),
        migrations.CreateModel(
            name='EditionDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edition_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
